### ISSUE TITLE
Both admin and subscribed user can not login

### ISSUE THREAD

**Issue by kekegg** [mblayman/conductor#386]
Hi, Matt,

I'm trying to run an instance of your website as a training. The signup process goes well after fixing several css, js issues. But after that, sign in always resulted in sign in page. After I create super user, this user also failed to log in. 

Do you have any idea what could be the reason?

**Comment by mblayman** [comment]
Hi, @kekegg. I appreciate your interest in the code. Sadly, I don't have the personal time to commit to fixing issues in clones.

I suspect something is not quite configured properly with authentication or session management in your environment. I'd suggest using the DevTools network tab to see what's going with the network requests. You could be seeing a bunch of redirects that are sending you back to the login page. That's the best I'm able to offer.

Good luck!
